# Generated by Django 4.2.4 on 2024-12-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
