# Generated by Django 4.2.4 on 2024-12-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_users_date_joined_users_is_active_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
